config/routes.rb
Rails.application.routes.draw do
  resources :weapons
  resources :ports
  resources :superlasers

end

app/models/port.rb
class Port < ActiveRecord::Base
  validates :name, presence: true
end

app/models/superlaser.rb
class Superlaser < ActiveRecord::Base
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ports_controller.rb
class PortsController < ApplicationController
  before_action :set_port, only: [:show, :edit, :update, :destroy]

  def index
    @ports = Port.all
  end

  def new
    @port = Port.new
  end

  def create
    @port = Port.new(port_params)

    respond_to do |format|
      if @port.save
        format.html { redirect_to @port, notice: 'Port was successfully created.' }
        format.json { render :show, status: :created, location: @port }
      else
        format.html { render :new }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @port.update(port_params)
        format.html { redirect_to @port, notice: 'Port was successfully updated.' }
        format.json { render :show, status: :ok, location: @port }
      else
        format.html { render :edit }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @port.destroy
    respond_to do |format|
      format.html { redirect_to ports_url, notice: 'Port was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_port
      @port = Port.find(params[:id])
    end
    
    def port_params
      params.require(:port).permit(:name, :type)
    end
end

app/controllers/superlasers_controller.rb
class SuperlasersController < ApplicationController
  before_action :set_superlaser, only: [:show, :edit, :update, :destroy]

  def index
    @superlasers = Superlaser.all
  end

  def show
  end

  def new
    @superlaser = Superlaser.new
  end

  def edit
  end

  def create
    @superlaser = Superlaser.new(superlaser_params)

    respond_to do |format|
      if @superlaser.save
        format.html { redirect_to @superlaser, notice: 'Superlaser was successfully created.' }
        format.json { render :show, status: :created, location: @superlaser }
      else
        format.html { render :new }
        format.json { render json: @superlaser.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @superlaser.update(superlaser_params)
        format.html { redirect_to @superlaser, notice: 'Superlaser was successfully updated.' }
        format.json { render :show, status: :ok, location: @superlaser }
      else
        format.html { render :edit }
        format.json { render json: @superlaser.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @superlaser.destroy
    respond_to do |format|
      format.html { redirect_to superlasers_url, notice: 'Superlaser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_superlaser
      @superlaser = Superlaser.find(params[:id])
    end

    def superlaser_params
      params.require(:superlaser).permit(:name)
    end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: [:show, :edit, :update, :destroy]

  def index
    @weapons = Weapon.all
  end

  def show
  end

  def new
    @weapon = Weapon.new
  end

  def edit
  end

  def create
    @weapon = Weapon.new(weapon_params)

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render :show, status: :created, location: @weapon }
      else
        format.html { render :new }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { render :show, status: :ok, location: @weapon }
      else
        format.html { render :edit }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @weapon.destroy
    respond_to do |format|
      format.html { redirect_to weapons_url, notice: 'Weapon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end

    def weapon_params
      params.require(:weapon).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/helpers/superlasers_helper.rb
module SuperlasersHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeathStar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ports/_form.html.erb
<%= form_for(@port) do |f| %>
  <% if @port.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@port.errors.count, "error") %> prohibited this port from being saved:</h2>

      <ul>
      <% @port.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ports/edit.html.erb
<h1>Editing Port</h1>

<%= render 'form' %>

<%= link_to 'Show', @port %> |
<%= link_to 'Back', ports_path %>

app/views/ports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ports.each do |port| %>
      <tr>
        <td><%= port.name %></td>
        <td><%= port.type %></td>
        <td><%= link_to 'Show', port %></td>
        <td><%= link_to 'Edit', edit_port_path(port) %></td>
        <td><%= link_to 'Destroy', port, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Port', new_port_path %>

app/views/ports/new.html.erb
<h1>New Port</h1>

<%= render 'form' %>

<%= link_to 'Back', ports_path %>

app/views/ports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @port.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @port.type %>
</p>

<%= link_to 'Edit', edit_port_path(@port) %> |
<%= link_to 'Back', ports_path %>

app/views/superlasers/_form.html.erb
<%= form_for(@superlaser) do |f| %>
  <% if @superlaser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@superlaser.errors.count, "error") %> prohibited this superlaser from being saved:</h2>

      <ul>
      <% @superlaser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/superlasers/edit.html.erb
<h1>Editing Superlaser</h1>

<%= render 'form' %>

<%= link_to 'Show', @superlaser %> |
<%= link_to 'Back', superlasers_path %>

app/views/superlasers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Superlasers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @superlasers.each do |superlaser| %>
      <tr>
        <td><%= superlaser.name %></td>
        <td><%= link_to 'Show', superlaser %></td>
        <td><%= link_to 'Edit', edit_superlaser_path(superlaser) %></td>
        <td><%= link_to 'Destroy', superlaser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Superlaser', new_superlaser_path %>

app/views/superlasers/new.html.erb
<h1>New Superlaser</h1>

<%= render 'form' %>

<%= link_to 'Back', superlasers_path %>

app/views/superlasers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @superlaser.name %>
</p>

<%= link_to 'Edit', edit_superlaser_path(@superlaser) %> |
<%= link_to 'Back', superlasers_path %>

app/views/weapons/_form.html.erb
<%= form_for(@weapon) do |f| %>
  <% if @weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
      <% @weapon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weapons/edit.html.erb
<h1>Editing Weapon</h1>

<%= render 'form' %>

<%= link_to 'Show', @weapon %> |
<%= link_to 'Back', weapons_path %>

app/views/weapons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weapons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weapons.each do |weapon| %>
      <tr>
        <td><%= weapon.name %></td>
        <td><%= link_to 'Show', weapon %></td>
        <td><%= link_to 'Edit', edit_weapon_path(weapon) %></td>
        <td><%= link_to 'Destroy', weapon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weapon', new_weapon_path %>

app/views/weapons/new.html.erb
<h1>New Weapon</h1>

<%= render 'form' %>

<%= link_to 'Back', weapons_path %>

app/views/weapons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weapon.name %>
</p>

<%= link_to 'Edit', edit_weapon_path(@weapon) %> |
<%= link_to 'Back', weapons_path %>